version: 1.0.{build}-{branch}

branches:
  only:
    - master

cache:
  - node_modules

environment:
  NOV: 4
  GITLAB_TRIGGER: https://gitlab.com/api/v3/projects/1151002/trigger/builds
  GITLAB_TOKEN:
    secure: 1lnMAQ+5fA2qlOUv4uZZIv7PMLqzLp7lPIV2tfQ+BGA=

platform:
  - x86

install:
  - ps: Install-Product node $env:NOV $env:PLATFORM
  - npm install
  - curl -fsSL https://github.com/ukoloff/bkrs/wiki/tools/ZD_Tools_1.3.zip -o src/zdtools.zip
  - 7z x src/zdtools.zip -osrc makezd.exe
  - curl -fsSL https://github.com/ukoloff/bkrs/wiki/tools/dictzip.exe -o src/dictzip.exe

build: off

before_test:
  - node -v
  - npm -v

test_script:
  - npm test
  - node lib/gitlab
  - node lib/fetch
  - npm start --tags=dsl
  - npm start

after_test:
  - src\makezd -cp1:65001 -cp2:65001 -a:src/abbreviations.txt src/articles.txt bkrs.zd
  - src\dictzip.exe -k src/b*.dsl
  - 7z a bkrs.zip ./src/b*.dsl ./extras/*.bmp ./src/*.yml
  - 7z a bkrs-min.zip ./src/*.dsl.dz ./extras/*.bmp ./src/*.yml

artifacts:
  - path: bkrs.zip
    name: BKRS for GoldenDict
    type: zip
  - path: bkrs-min.zip
    name: BKRS for Android GoldenDict
    type: zip
  - path: bkrs.zd
    name: BKRS for Dictan
  - path: src/*.yml
    name: Some statistics
