# Default tags mapping

tag: span
tags:
  b: b
  i: i
  ref: r
  m: div
  m1: div
  m2: >
    div style="margin-left: 1em;"
  m3: >
    div style="margin-left: 2em;"
  m4: >
    div style="margin-left: 3em;"
  m5: >
    div style="margin-left: 4em;"
  '*': font color="red"
  p:  font color="green"
  ex: font color='navy'
  e:  font color='navy'
  c:  font
  c red: font color='red'
  c black: font color='black'
  c green: font color='green'
  c brown: font color='brown'
  c violet: font color='violet'
  c crimson: font color='crimson'
  c gray: font color='gray'
py:
  ref: r
  wrap: li
