# Default tags mapping

tag: span
zd:
  wrap: div
  br:   []
tags:
  b: b
  i: i
  u: u
  ref: r
  m: &m >
    div style="margin-top: 1em;"
  m0: *m
  m1: >
    div style="margin-top: 1em; margin-left: 1em;"
  m2: >
    div style="margin-left: 2em;"
  m3: >
    div style="margin-left: 3em;"
  m4: >
    div style="margin-left: 4em;"
  m5: >
    div style="margin-left: 5em;"
  m6: >
    div style="margin-left: 6em;"
  m7: >
    div style="margin-left: 7em;"
  m8: >
    div style="margin-left: 8em;"
  m9: >
    div style="margin-left: 9em;"
  '*': font color="navy"
  p:  font color="green"
  ex: font color='gray'
  e:  font color='gray'
  c: font color='green'
  c red: font color='red'
  c black: font color='black'
  c green: font color='green'
  c brown: font color='brown'
  c violet: font color='violet'
  c crimson: font color='crimson'
  c gray: font color='gray'
